"""Add confirmed field to registrations

Revision ID: 096656a91720
Revises: bda9a423c7c2
Create Date: 2025-12-13 18:41:37.355622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096656a91720'
down_revision = 'bda9a423c7c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

