"""Add notification buttons and recipients

Revision ID: 4a84897311c0
Revises: 8c894becc78f
Create Date: 2025-12-13 18:20:56.538924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a84897311c0'
down_revision = '8c894becc78f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_buttons', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('notification_recipients', sa.JSON(), nullable=True))
    
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('confirmed')
    
    with op.batch_alter_table('event_notifications', schema=None) as batch_op:
        batch_op.drop_column('notification_recipients')
        batch_op.drop_column('include_buttons')
    # ### end Alembic commands ###

