"""Add max_participants to events

Revision ID: a4d22b0cf1b4
Revises: 096656a91720
Create Date: 2025-12-13 19:41:39.345035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d22b0cf1b4'
down_revision = '096656a91720'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('max_participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'max_participants')
    # ### end Alembic commands ###

