"""Add photo to events

Revision ID: bda9a423c7c2
Revises: 4a84897311c0
Create Date: 2025-12-13 18:30:20.568337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda9a423c7c2'
down_revision = '4a84897311c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_file_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo_file_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('photo_file_ids')
        batch_op.drop_column('photo_file_id')
    # ### end Alembic commands ###

